import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "HotelGuard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="color-scheme" content="light dark" />
        <style>{`
          html { background: #f8fafc; }
          @media (prefers-color-scheme: dark) {
            html { background: #07090f; }
          }
          html.dark { background: #07090f; }
          html:not(.dark) { background: #f8fafc; }
          body { background: transparent; }
        `}</style>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  var key = "dashboard_theme_mode";
                  var stored = localStorage.getItem(key);
                  var mode = (stored === "night" || stored === "system" || stored === "day") ? stored : "system";
                  var prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
                  var dark = mode === "night" || (mode === "system" && prefersDark);
                  var root = document.documentElement;
                  root.classList.toggle("dark", dark);
                  root.style.backgroundColor = dark ? "#07090f" : "#f8fafc";
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className="[--font-geist-sans:ui-sans-serif] [--font-geist-mono:ui-monospace] antialiased"
      >
        {children}
      </body>
    </html>
  );
}
